from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 1018)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "border-image:url(./ui/background.png)")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum,
            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_1.addItem(spacerItem)
        self.gridLayout_1.addLayout(self.verticalLayout_1, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.result = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.result.setFont(font)
        self.result.setAutoFillBackground(False)
        self.result.setStyleSheet("color: red;border-image:url()")
        self.result.setText("")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.verticalLayout_2.addWidget(self.result)
        self.gridLayout_1.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(60, 80))
        self.label.setMaximumSize(QtCore.QSize(1280, 960))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border-image:url()")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_1.addWidget(self.label, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet(
            "border-image:url();color: yellow;border:none;")
        self.lcdNumber.setDigitCount(20)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout_3.addWidget(self.lcdNumber)
        self.gridLayout_1.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.gridLayout_1.setRowStretch(0, 1)
        self.gridLayout_1.setRowStretch(1, 4)
        self.gridLayout_1.setRowStretch(2, 8)
        self.gridLayout_1.setRowStretch(3, 4)
        self.gridLayout.addLayout(self.gridLayout_1, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 26))
        self.menubar.setObjectName("menubar")
        self.Setup = QtWidgets.QMenu(self.menubar)
        self.Setup.setObjectName("Setup")
        self.Manage = QtWidgets.QMenu(self.menubar)
        self.Manage.setObjectName("Manage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Open_cam = QtWidgets.QAction(MainWindow)
        self.Open_cam.setObjectName("Open_cam")
        self.Open_face_regionizer = QtWidgets.QAction(MainWindow)
        self.Open_face_regionizer.setObjectName("Open_face_regionizer")
        self.Face_data_get = QtWidgets.QAction(MainWindow)
        self.Face_data_get.setObjectName("Face_data_get")
        self.Train_face_data = QtWidgets.QAction(MainWindow)
        self.Train_face_data.setObjectName("Train_face_data")
        self.Login = QtWidgets.QAction(MainWindow)
        self.Login.setObjectName("Login")
        self.Register = QtWidgets.QAction(MainWindow)
        self.Register.setObjectName("Register")
        self.Signout = QtWidgets.QAction(MainWindow)
        self.Signout.setObjectName("Signout")
        self.CloseWindow = QtWidgets.QAction(MainWindow)
        self.CloseWindow.setObjectName("CloseWindow")
        self.AutoRun = QtWidgets.QAction(MainWindow)
        self.AutoRun.setObjectName("AutoRun")
        self.Setup.addAction(self.Open_cam)
        self.Setup.addAction(self.Open_face_regionizer)
        self.Setup.addAction(self.Face_data_get)
        self.Setup.addAction(self.Train_face_data)
        self.Manage.addAction(self.Login)
        self.Manage.addAction(self.Register)
        self.Manage.addAction(self.Signout)
        self.Manage.addAction(self.AutoRun)
        self.Manage.addAction(self.CloseWindow)
        self.menubar.addAction(self.Manage.menuAction())
        self.menubar.addAction(self.Setup.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setWindowIcon(QtGui.QIcon("ui/app_icon.png"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "门禁系统-YOLOv5"))
        self.label.setText(_translate("MainWindow", "未启动"))
        self.Setup.setTitle(_translate("MainWindow", "设置"))
        self.Manage.setTitle(_translate("MainWindow", "管理"))
        self.Open_cam.setText(_translate("MainWindow", "开启摄像头"))
        self.Open_face_regionizer.setText(
            _translate("MainWindow", "启动人脸识别"))
        self.Face_data_get.setText(_translate("MainWindow", "录入人脸数据"))
        self.Train_face_data.setText(_translate("MainWindow", "训练人脸模型"))
        self.Login.setText(_translate("MainWindow", "登录"))
        self.Register.setText(_translate("MainWindow", "注册"))
        self.Signout.setText(_translate("MainWindow", "注销"))
        self.CloseWindow.setText(_translate("MainWindow", "退出程序"))
        self.AutoRun.setText(_translate("MainWindow", "自动运行"))
